name: Base Image PHP

on:
  workflow_dispatch:

jobs:
  Base:
    strategy:
      matrix:
        build: [
          "5.6"
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.9"
      # - name: Setup docker-slim
      #   run: curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
      - name: Setup docker-squash
        run: pip install --user https://github.com/goldmann/docker-squash/archive/master.zip
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker
        run : |
          cd base/${{ matrix.build }}/
          docker build -f Dockerfile -t jpratama7/php-fpm:build-fat .
          docker-squash -v -t jpratama7/php-fpm:${{ matrix.build }}-latest jpratama7/php-fpm:build-fat
          docker push jpratama7/php-fpm:${{ matrix.build }}-latest
          docker-squash -v -t jpratama7/php-fpm:${{ matrix.build }}-${{ steps.date.outputs.date }} jpratama7/php-fpm:build-fat
          docker push jpratama7/php-fpm:${{ matrix.build }}-${{ steps.date.outputs.date }}